# Combining Data

Practice combining data from two different data sets. In the same folder as this Jupyter notebook, there are two csv files:
* rural_population_percent.csv
* electricity_access_percent.csv

They both come from the World Bank Indicators data. 
* https://data.worldbank.org/indicator/SP.RUR.TOTL.ZS
* https://data.worldbank.org/indicator/EG.ELC.ACCS.ZS

The rural populaton data represents the percent of a country's population that is rural over time. The electricity access data shows the percentage of people with access to electricity.

In this exercise, you will combine these two data sets together into one pandas data frame.

# Exercise 1

Combine the two data sets using the [pandas concat method](https://pandas.pydata.org/pandas-docs/stable/merging.html). In other words, find the union of the two data sets.

In [13]:
# TODO: import the pandas library
import pandas as pd

# TODO: read in each csv file into a separate variable
# HINT: remember from the Extract material that these csv file have some formatting issues
# HINT: The file paths are 'rural_population_percent.csv' and 'electricity_access_percent.csv'
df_rural = pd.read_csv('rural_population_percent.csv', skiprows=4)
df_electricity = pd.read_csv('electricity_access_percent.csv', skiprows=4)

# TODO: remove the 'Unnamed:62' column from each data set
df_rural.drop(['Unnamed: 62'], axis=1, inplace=True)
df_electricity.drop(['Unnamed: 62'], axis=1, inplace=True)

# TODO: combine the two data sets together using the concat method
# In other words, all of the rows of df_rural will come first
# followed by all the rows in df_electricity. This is possible to do
# because they both have the same column names.


pd.concat([df_rural, df_electricity], axis=1)

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2008,2009,2010,2011,2012,2013,2014,2015,2016,2017
0,Aruba,ABW,Rural population (% of total population),SP.RUR.TOTL.ZS,49.224000,49.239000,49.254000,49.270000,49.285000,49.300000,...,93.086166,93.354546,93.356292,93.942375,94.255814,94.578262,94.906723,95.238182,95.570145,NaN
1,Afghanistan,AFG,Rural population (% of total population),SP.RUR.TOTL.ZS,91.779000,91.492000,91.195000,90.890000,90.574000,90.250000,...,42.400000,44.854885,42.700000,43.222019,69.100000,67.259552,89.500000,71.500000,84.137138,NaN
2,Angola,AGO,Rural population (% of total population),SP.RUR.TOTL.ZS,89.565000,89.202000,88.796000,88.376000,87.942000,87.496000,...,31.268013,32.382469,33.514950,34.600000,35.821964,36.990490,32.000000,42.000000,40.520607,NaN
3,Albania,ALB,Rural population (% of total population),SP.RUR.TOTL.ZS,69.295000,69.057000,68.985000,68.914000,68.842000,68.770000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
4,Andorra,AND,Rural population (% of total population),SP.RUR.TOTL.ZS,41.550000,39.017000,36.538000,34.128000,31.795000,29.555000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
5,Arab World,ARB,Rural population (% of total population),SP.RUR.TOTL.ZS,68.708026,67.965580,67.219820,66.450960,65.652964,64.813430,...,85.432827,85.189815,86.136134,86.782683,87.288244,88.389705,88.076774,88.517967,88.768654,NaN
6,United Arab Emirates,ARE,Rural population (% of total population),SP.RUR.TOTL.ZS,26.500000,25.617000,24.752000,23.907000,23.081000,22.277000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
7,Argentina,ARG,Rural population (% of total population),SP.RUR.TOTL.ZS,26.389000,25.783000,25.233000,24.691000,24.156000,23.631000,...,97.934128,98.363365,98.820000,99.216164,99.584412,99.837128,99.959244,99.995209,100.000000,NaN
8,Armenia,ARM,Rural population (% of total population),SP.RUR.TOTL.ZS,48.725000,47.853000,46.981000,46.111000,45.242000,44.378000,...,99.415649,99.519814,99.800000,99.767151,99.878876,99.954056,99.988976,100.000000,100.000000,NaN
9,American Samoa,ASM,Rural population (% of total population),SP.RUR.TOTL.ZS,33.789000,33.359000,32.932000,32.507000,32.084000,31.666000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Antigua and Barbuda,ATG,Rural population (% of total population),SP.RUR.TOTL.ZS,60.344000,60.960000,61.573000,62.183000,62.789000,63.390000,...,93.299408,93.764198,94.247009,94.552014,95.254692,95.773552,96.298416,96.826294,97.354668,NaN
11,Australia,AUS,Rural population (% of total population),SP.RUR.TOTL.ZS,18.471000,18.059000,17.663000,17.273000,16.890000,16.515000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
12,Austria,AUT,Rural population (% of total population),SP.RUR.TOTL.ZS,35.280000,35.186000,35.137000,35.087000,35.038000,34.989000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
13,Azerbaijan,AZE,Rural population (% of total population),SP.RUR.TOTL.ZS,47.337000,47.636000,47.936000,48.236000,48.536000,48.836000,...,99.741806,99.884735,99.965675,99.900000,99.999710,100.000000,100.000000,100.000000,100.000000,NaN
14,Burundi,BDI,Rural population (% of total population),SP.RUR.TOTL.ZS,97.923000,97.885000,97.846000,97.807000,97.767000,97.706000,...,4.800000,5.341904,5.300000,5.938580,6.500000,6.583319,7.000000,7.252090,7.588477,NaN
15,Belgium,BEL,Rural population (% of total population),SP.RUR.TOTL.ZS,7.540000,7.446000,7.321000,7.165000,7.012000,6.863000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
16,Benin,BEN,Rural population (% of total population),SP.RUR.TOTL.ZS,90.725000,90.144000,89.530000,88.882000,88.199000,87.481000,...,30.621239,31.926792,34.200000,36.900000,38.400000,37.299206,34.100000,40.033478,41.402615,NaN
17,Burkina Faso,BFA,Rural population (% of total population),SP.RUR.TOTL.ZS,95.300000,95.204000,95.107000,95.007000,94.905000,94.802000,...,13.779394,14.410441,13.100000,15.723602,16.399708,17.084827,19.200000,18.470081,19.164713,NaN
18,Bangladesh,BGD,Rural population (% of total population),SP.RUR.TOTL.ZS,94.865000,94.722000,94.502000,94.273000,94.036000,93.789000,...,51.249775,53.632854,55.260000,59.600000,60.878216,61.500000,62.400000,68.204681,75.920000,NaN
19,Bulgaria,BGR,Rural population (% of total population),SP.RUR.TOTL.ZS,62.900000,61.218000,59.506000,57.770000,56.013000,54.245000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
20,Bahrain,BHR,Rural population (% of total population),SP.RUR.TOTL.ZS,17.680000,17.663000,17.645000,17.628000,17.611000,17.500000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
21,"Bahamas, The",BHS,Rural population (% of total population),SP.RUR.TOTL.ZS,40.288000,39.546000,38.807000,38.074000,37.358000,36.657000,...,98.753685,99.182266,99.560989,99.825653,99.955795,99.994736,100.000000,100.000000,100.000000,NaN
22,Bosnia and Herzegovina,BIH,Rural population (% of total population),SP.RUR.TOTL.ZS,80.960000,80.314000,79.563000,78.791000,77.996000,77.183000,...,99.580040,99.725403,99.855759,99.705781,99.986618,99.998489,100.000000,100.000000,100.000000,NaN
23,Belarus,BLR,Rural population (% of total population),SP.RUR.TOTL.ZS,67.599000,66.478000,65.337000,64.178000,63.000000,61.873000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
24,Belize,BLZ,Rural population (% of total population),SP.RUR.TOTL.ZS,45.972000,46.280000,46.590000,46.899000,47.210000,47.519000,...,90.615021,90.772812,89.917224,91.681736,91.342323,91.554184,91.772057,91.800000,92.214317,NaN
25,Bermuda,BMU,Rural population (% of total population),SP.RUR.TOTL.ZS,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
26,Bolivia,BOL,Rural population (% of total population),SP.RUR.TOTL.ZS,63.238000,62.941000,62.643000,62.344000,62.043000,61.743000,...,84.674991,86.765597,84.294815,88.335943,90.387375,89.505686,90.038729,91.522822,93.039131,NaN
27,Brazil,BRA,Rural population (% of total population),SP.RUR.TOTL.ZS,53.861000,52.878000,51.901000,50.922000,49.941000,48.963000,...,98.526625,98.856938,98.883057,99.328691,99.519494,99.575151,99.650247,99.710902,100.000000,NaN
28,Barbados,BRB,Rural population (% of total population),SP.RUR.TOTL.ZS,63.223000,63.151000,63.078000,63.005000,62.932000,62.859000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
29,Brunei Darussalam,BRN,Rural population (% of total population),SP.RUR.TOTL.ZS,56.599000,54.772000,52.930000,51.080000,49.224000,47.375000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,Latin America & the Caribbean (IDA & IBRD coun...,TLA,Rural population (% of total population),SP.RUR.TOTL.ZS,50.988145,50.182637,49.366194,48.547377,47.723476,46.949219,...,95.186103,95.441090,95.801052,96.161153,96.522279,96.922377,96.936467,97.183215,97.742979,NaN
235,Timor-Leste,TLS,Rural population (% of total population),SP.RUR.TOTL.ZS,89.909000,89.757000,89.489000,89.215000,88.934000,88.647000,...,41.100101,43.844738,38.000000,49.385078,52.174774,54.973484,57.778198,67.281534,63.394138,NaN
236,Middle East & North Africa (IDA & IBRD countries),TMN,Rural population (% of total population),SP.RUR.TOTL.ZS,66.117373,65.397398,64.677987,63.954108,63.219212,62.447471,...,94.760384,95.008710,95.297786,95.910895,96.376501,97.506184,96.325711,97.493216,97.671447,NaN
237,Tonga,TON,Rural population (% of total population),SP.RUR.TOTL.ZS,82.448000,82.071000,81.688000,81.299000,80.902000,80.501000,...,90.780235,91.511932,92.261650,92.175456,92.800000,94.588905,95.380676,96.175453,97.020000,NaN
238,South Asia (IDA & IBRD),TSA,Rural population (% of total population),SP.RUR.TOTL.ZS,83.264979,83.133571,82.946153,82.756975,82.561748,82.366251,...,70.641563,74.025057,75.117519,69.326529,79.352935,79.318324,81.448690,86.513987,85.569150,NaN
239,Sub-Saharan Africa (IDA & IBRD countries),TSS,Rural population (% of total population),SP.RUR.TOTL.ZS,85.356483,85.052421,84.742726,84.414051,84.070101,83.715700,...,31.973327,32.490060,32.633561,34.880128,35.770348,36.542705,37.760013,38.459815,42.813754,NaN
240,Trinidad and Tobago,TTO,Rural population (% of total population),SP.RUR.TOTL.ZS,82.651000,83.288000,83.907000,84.507000,85.090000,85.653000,...,97.827667,99.000000,99.298363,99.736145,99.936935,99.992935,100.000000,100.000000,100.000000,NaN
241,Tunisia,TUN,Rural population (% of total population),SP.RUR.TOTL.ZS,62.489000,62.050000,61.609000,61.167000,60.721000,60.276000,...,99.400000,99.500000,99.500000,99.500000,99.500000,99.700000,99.800000,100.000000,100.000000,NaN
242,Turkey,TUR,Rural population (% of total population),SP.RUR.TOTL.ZS,68.485000,67.936000,67.402000,66.863000,66.320000,65.773000,...,98.806900,99.310745,100.000000,99.910782,99.985657,99.999252,100.000000,100.000000,100.000000,NaN
243,Tuvalu,TUV,Rural population (% of total population),SP.RUR.TOTL.ZS,84.105000,83.556000,82.992000,82.413000,81.817000,81.207000,...,96.450043,96.779938,97.127861,97.490799,97.671777,98.249725,98.639702,99.032677,99.426155,NaN
244,Tanzania,TZA,Rural population (% of total population),SP.RUR.TOTL.ZS,94.754000,94.606000,94.453000,94.296000,94.135000,93.970000,...,11.500000,11.200000,14.800000,14.200000,15.300000,16.400000,18.910179,18.500000,32.800000,NaN
245,Uganda,UGA,Rural population (% of total population),SP.RUR.TOTL.ZS,95.583000,95.383000,95.174000,94.955000,94.727000,94.491000,...,13.383857,10.000000,14.769371,14.600000,16.214964,13.900000,20.400000,18.500000,26.700000,NaN
246,Ukraine,UKR,Rural population (% of total population),SP.RUR.TOTL.ZS,53.208000,52.458000,51.706000,50.954000,50.200000,49.351000,...,99.782707,99.872482,99.945076,99.985046,99.867491,100.000000,100.000000,100.000000,100.000000,NaN
247,Upper middle income,UMC,Rural population (% of total population),SP.RUR.TOTL.ZS,72.481711,71.644487,70.914989,70.286835,69.643234,69.441784,...,97.951365,98.322811,98.775502,98.866005,99.059438,99.214211,99.235891,99.268934,99.379714,NaN
248,Uruguay,URY,Rural population (% of total population),SP.RUR.TOTL.ZS,19.759000,19.538000,19.319000,19.101000,18.886000,18.672000,...,98.784355,98.830696,98.989487,99.170000,99.349075,99.611808,99.657085,99.709480,100.000000,NaN
249,United States,USA,Rural population (% of total population),SP.RUR.TOTL.ZS,30.004000,29.623000,29.243000,28.866000,28.492000,28.121000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
250,Uzbekistan,UZB,Rural population (% of total population),SP.RUR.TOTL.ZS,66.022000,65.762000,65.500000,65.238000,64.975000,64.711000,...,99.902954,99.955498,99.986694,99.997910,99.999908,100.000000,100.000000,100.000000,100.000000,NaN
251,St. Vincent and the Grenadines,VCT,Rural population (% of total population),SP.RUR.TOTL.ZS,74.057000,73.606000,73.149000,72.686000,72.219000,71.748000,...,90.470222,91.837242,93.222282,94.622345,96.034424,97.455513,98.598648,99.455063,100.000000,NaN
252,"Venezuela, RB",VEN,Rural population (% of total population),SP.RUR.TOTL.ZS,38.387000,37.125000,36.067000,35.023000,33.991000,32.978000,...,98.630798,98.710304,98.807846,98.840000,99.044968,99.178551,99.318146,99.460739,99.603836,NaN
253,British Virgin Islands,VGB,Rural population (% of total population),SP.RUR.TOTL.ZS,87.772000,87.382000,86.981000,86.570000,86.146000,85.713000,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
254,Virgin Islands (U.S.),VIR,Rural population (% of total population),SP.RUR.TOTL.ZS,43.523000,42.136000,40.759000,39.396000,38.048000,36.721000,...,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,NaN
255,Vietnam,VNM,Rural population (% of total population),SP.RUR.TOTL.ZS,85.300000,84.969000,84.631000,84.286000,83.936000,83.579000,...,95.208260,96.100000,97.591133,99.000000,100.000000,100.000000,99.200000,100.000000,100.000000,NaN
256,Vanuatu,VUT,Rural population (% of total population),SP.RUR.TOTL.ZS,89.596000,89.417000,89.235000,89.050000,88.862000,88.671000,...,33.873974,33.291115,36.898365,38.434589,39.982830,31.700000,43.103348,44.669613,57.820000,NaN
257,World,WLD,Rural population (% of total population),SP.RUR.TOTL.ZS,66.427899,65.914790,65.472800,65.085718,64.692040,64.470390,...,82.278317,83.211382,83.539093,82.504609,85.041356,85.163456,85.690892,87.028468,87.351269,NaN
258,Samoa,WSM,Rural population (% of total population),SP.RUR.TOTL.ZS,81.074000,81.014000,80.939000,80.859000,80.779000,80.699000,...,94.694328,97.900000,96.606010,96.668575,98.504707,99.255646,97.900000,99.938278,100.000000,NaN
259,Kosovo,XKX,Rural population (% of total population),SP.RUR.TOTL.ZS,NaN,NaN,NaN,NaN,NaN,NaN,...,97.794670,98.377060,0.000000,99.430435,99.773651,99.942505,99.993134,100.000000,100.000000,NaN
260,"Yemen, Rep.",YEM,Rural population (% of total population),SP.RUR.TOTL.ZS,90.900000,90.541000,90.169000,89.784000,89.386000,88.974000,...,60.386539,61.751400,63.134281,64.532181,65.942101,75.600000,66.100000,70.213905,71.642349,NaN
261,South Africa,ZAF,Rural population (% of total population),SP.RUR.TOTL.ZS,53.381000,53.207000,53.094000,52.980000,52.866000,52.752000,...,81.900000,82.700000,82.900000,84.700000,85.300000,85.400000,86.000000,85.500000,84.200000,NaN
262,Zambia,ZMB,Rural population (% of total population),SP.RUR.TOTL.ZS,81.855000,81.049000,80.215000,79.288000,77.985000,76.628000,...,22.714685,23.235649,22.000000,24.328644,24.894667,25.469702,27.900000,31.100000,27.219337,NaN
263,Zimbabwe,ZWE,Rural population (% of total population),SP.RUR.TOTL.ZS,87.392000,87.179000,86.918000,86.422000,85.908000,85.380000,...,35.457310,43.369082,36.063057,36.900000,36.728878,37.076813,32.300000,33.700000,38.145138,NaN

# Exercise 2 (Challenge)

This exercise is more challenging.

Combine the two datas in the csv file together so that the output looks like the following:

|Country Name|Country Code|Year|Rural_Value|Electricity_Value|
|--|--|--|--|--|--|
|Aruba|ABW|1960|49.224|49.239|
... etc.

Order the results in the dataframe by country and then by year

Here are a few pandas methods that should be helpful:
* [melt](http://pandas.pydata.org/pandas-docs/stable/generated/pandas.melt.html)
* [drop](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.drop.html)
* [merge](https://pandas.pydata.org/pandas-docs/version/0.23/generated/pandas.DataFrame.merge.html)
* [sort_values](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sort_values.html)

HINT: You can use country name, country code, and the year as common keys between the data sets

In [27]:
# TODO: merge the data sets together according to the instructions. First, use the 
# melt method to change the formatting of each data frame so that it looks like this:
# Country Name, Country Code, Year, Rural Value
# Country Name, Country Code, Year, Electricity Value
df_rural_melt = df_rural.melt(id_vars=['Country Name', 'Country Code', \
                                       'Indicator Name', 'Indicator Code'], \
                              var_name='Year', value_name='Rural Value')

df_electricity_melt = df_electricity.melt(id_vars=['Country Name', 'Country Code', \
                                                   'Indicator Name', 'Indicator Code'], \
                                          var_name='Year', value_name='Electricity Value')

# TODO: drop any columns from the data frames that aren't needed
df_rural_melt.drop(['Indicator Name', 'Indicator Code'], axis=1, inplace=True)
df_electricity_melt.drop(['Indicator Name', 'Indicator Code'], axis=1, inplace=True)

# TODO: merge the data frames together based on their common columns
# in this case, the common columns are Country Name, Country Code, and Year
df_merge = df_rural_melt.merge(df_electricity_melt, how='outer', on=['Country Name', 'Country Code', 'Year'])
df_merge
# TODO: sort the results by country and then by year
df_combined = df_merge.sort_values(['Country Code', 'Year'])
df_combined

      Country Name Country Code  Year  Rural Value  Electricity Value
0            Aruba          ABW  1960       49.224                NaN
264          Aruba          ABW  1961       49.239                NaN
528          Aruba          ABW  1962       49.254                NaN
792          Aruba          ABW  1963       49.270                NaN
1056         Aruba          ABW  1964       49.285                NaN
1320         Aruba          ABW  1965       49.300                NaN
1584         Aruba          ABW  1966       49.315                NaN
1848         Aruba          ABW  1967       49.330                NaN
2112         Aruba          ABW  1968       49.346                NaN
2376         Aruba          ABW  1969       49.361                NaN
2640         Aruba          ABW  1970       49.376                NaN
2904         Aruba          ABW  1971       49.391                NaN
3168         Aruba          ABW  1972       49.407                NaN
3432         Aruba          ABW  1973       49.422                NaN
3696         Aruba          ABW  1974       49.437                NaN
3960         Aruba          ABW  1975       49.452                NaN
4224         Aruba          ABW  1976       49.468                NaN
4488         Aruba          ABW  1977       49.483                NaN
4752         Aruba          ABW  1978       49.498                NaN
5016         Aruba          ABW  1979       49.513                NaN
5280         Aruba          ABW  1980       49.528                NaN
5544         Aruba          ABW  1981       49.544                NaN
5808         Aruba          ABW  1982       49.559                NaN
6072         Aruba          ABW  1983       49.574                NaN
6336         Aruba          ABW  1984       49.589                NaN
6600         Aruba          ABW  1985       49.605                NaN
6864         Aruba          ABW  1986       49.620                NaN
7128         Aruba          ABW  1987       49.635                NaN
7392         Aruba          ABW  1988       49.650                NaN
7656         Aruba          ABW  1989       49.665                NaN
...            ...          ...   ...          ...                ...
7655      Zimbabwe          ZWE  1988       72.476                NaN
7919      Zimbabwe          ZWE  1989       71.750                NaN
8183      Zimbabwe          ZWE  1990       71.012          30.357832
8447      Zimbabwe          ZWE  1991       70.262          30.718805
8711      Zimbabwe          ZWE  1992       69.501          28.200000
8975      Zimbabwe          ZWE  1993       69.060          31.436678
9239      Zimbabwe          ZWE  1994       68.665          28.100000
9503      Zimbabwe          ZWE  1995       68.268          32.130077
9767      Zimbabwe          ZWE  1996       67.868          32.459949
10031     Zimbabwe          ZWE  1997       67.466          32.774529
10295     Zimbabwe          ZWE  1998       67.061          33.070751
10559     Zimbabwe          ZWE  1999       66.653          38.400000
10823     Zimbabwe          ZWE  2000       66.242          33.597420
11087     Zimbabwe          ZWE  2001       65.830          33.830868
11351     Zimbabwe          ZWE  2002       65.415          34.200000
11615     Zimbabwe          ZWE  2003       65.521          34.266785
11879     Zimbabwe          ZWE  2004       65.706          34.481380
12143     Zimbabwe          ZWE  2005       65.890          34.701820
12407     Zimbabwe          ZWE  2006       66.074          37.200000
12671     Zimbabwe          ZWE  2007       66.257          35.184479
12935     Zimbabwe          ZWE  2008       66.440          35.457310
13199     Zimbabwe          ZWE  2009       66.622          43.369082
13463     Zimbabwe          ZWE  2010       66.804          36.063057
13727     Zimbabwe          ZWE  2011       66.985          36.900000
13991     Zimbabwe          ZWE  2012       67.166          36.728878
14255     Zimbabwe          ZWE  2013       67.346          37.076813
14519     Zimbabwe          ZWE  2014       67.499          32.300000
14783     Zimbabwe          ZWE  2015       67.624          33.700000
15047     Zimbabwe          ZWE  2016       67.723          38.145138
15311     Zimbabwe          ZWE  2017       67.793                NaN

[15312 rows x 5 columns]